version: "3"
services:
    backup_write:
        build: ./backup_write/
        hostname: backup_write
        volumes:
            - /var/lib/backupd:/var/lib/backupd
    backup_read:
        build: ./backup_read/
        hostname: backup_read
        volumes:
            - /var/lib/backupd:/home/reader/Backups:ro
